export const TRUSTED_SITES = `aaabackstage.com
murosdeabsenta.com
abductionradiation.tumblr.com
acidstag.com
acidted.wordpress.com
residentadvisor.net
addtowantlist.com
adobeandteardrops.com
africanpaper.com
afropunk.com
pan-african-music.com
passiveaggressive.dk
takethesongsandrun.wordpress.com
survivingthegoldenage.com
weallwantsomeone.org
getalternative.com
alt77.com
unblogallaradio.blogspot.com
all-aroundsound.blogspot.com
americana-uk.com
ambientblog.net
ambiancejeune.com
amthenfm.wordpress.com
analoguetrash.com
anotherwhiskyformisterbukowski.com
apathyandexhaustion.com
aquariumdrunkard.com
aqnb.com
arcana.fm
asianmandan.com
atwoodmagazine.com
atcostmag.tumblr.com
austintownhall.com
daily.bandcamp.com
banbantonton.com
ballofwax.org
beatburguer.com
beautifulsongoftheweek.com
beatradar.com
beatsperminute.com
beatinmybones.com
beehy.pe
berkeleyplaceblog.com
blackplastic.co.uk
boredinpittsburgh.home.blog
boltingbits.com
brooklynvegan.com
breakingmorewaves.blogspot.com
brutalresonance.com
brightonmusicblog.co.uk
buffablog.com
burlveneer-music.tumblr.com
buzzbands.la
castthedice.org
caughtbytheriver.net
canthisevenbecalledmusic.com
cerealandsounds.com
chordblossom.com
chicagoreader.com
christmasagogo.blogspot.com
christmasunderground.com
clunkmag.com
clashmusic.com
couvrexchefs.com
consequenceofsound.net
covermesongs.com
coolmusicandthings.co.uk
coast-is-clear.blogspot.com
cougarmicrobes.com
concreteopinions.com
commontime.club
cruelrhythm.tumblr.com
crackmagazine.net
cupsncakespod.com
culturedarm.com
dansendeberen.be
darkeninheart.com
datatransmission.co.uk
dandigs.com
decibelmagazine.com
destroyexist.com
deephouseamsterdam.com
digitalhigh.blog
digger.mx
digitalinberlin.de
disquiet.com
districtmagazine.ie
elrocco.blogspot.com
didnotchart.blogspot.com
dominionated.ca
doubtfulsounds.net
dodmagazine.es
doyoulikethatsong.com
dustedmagazine.tumblr.com
dubhed.blogspot.com
dubdotdash.blogspot.com
dustedandsocial.tumblr.com
dustyorgan.com
eartothegroundmusic.co
eartapas.tumblr.com
echoesanddust.com
edmreviewer.com
electronica.org.uk
electricsoundofjoy.com
electrozombies.com
electronicaandroll.com
eldescafeinado.com
escafandrista-musical.com
everythingisnoise.net
exclaim.ca
faetonmusic.com
fadeawayradiate.com
fatroland.com
feckingbahamas.com
filtermexico.com
fillessourires.com
fingertipsmusic.com
fleamarketfunk.com
fluid-radio.co.uk
fluxblog.org
fortherabbits.net
fourfourmag.com
focushiphop.com
folkradio.co.uk
freshonthenet.co.uk
frohfroh.de
fruitandgroovescollective.com
futurismrestated.substack.com
furtherdot.com
glamglare.com
glidemagazine.com
godisinthetvzine.co.uk
gobsmag.nl
wearegoingsolo.com
gorillavsbear.net
grandgood.com
groove.de
gtqlizer.blogspot.com
grauu.com
grungecake.com
grimygoods.com
takethesongsandrun.wordpress.com
hardofhearingmusic.com
herecomestheflood.com
heavyblogisheavy.com
reviews.headphonecommute.com
highclouds.org
hi54.blog
houseoflords.xyz
houseofplates.com
holysoul.tumblr.com
hrmnypresents.co.uk
ifitbeyourwill.ca
iggymagazine.com
ilictronix.blogspot.com
immersiveatlanta.com
imperfectfifth.com
indieforbunnies.com
indieobsessive.blogspot.com
inverted-audio.com
indieshuffle.com
indieisnotagenre.com
invisibleoranges.com
inn8.net
irregulardreamscanada.wordpress.com
janglepophub.home.blog
jazziz.com
joyzineuk.wordpress.com
jsound.tumblr.com
kaltblut-magazine.com
kcrw.com
keepwalkingmusic.com
kexp.org
keytarsandviolins.blogspot.com
kidwithavinyl.wordpress.com
klofmag.com
krachundso.blogspot.com
lazy-i.com
levisiteuronline.com
lecanalauditif.ca
leftofthedial.fm
earslend.blogspot.com
louderthanwar.com
loudwomen.org
loudnessblog.com
loudandquiet.com
lostturntable.com
manierenversagen.de
machinemusic.net
madmackerel.wordpress.com
metalsucks.net
music.metafilter.com
medellinstyle.com
unblogallaradio.blogspot.com
mindies.es
microgenremusic.com
mixmag.net
miojoindie.com.br
monkeyboxing.com
monolithcocktail.com
mowno.com
molarsmolars.com
mookidmusic.com
mp3hugger.com
mutantzones.blogspot.com
musicyouwannalistento.blogspot.com
musicwontsaveyou.com
murosdeabsenta.com
musicismysanctuary.com
yamamiya.wordpress.com
musicmap.global
myblogclicheislive.blogspot.com
newfeeling.ca
nichemusic.info
nitestylez.de
nialler9.com
nocleansinging.com
notransmission.com
nobells.blog
nocountryfornewnashville.com
nbhap.com
obscuresound.com
onechord.net
orbmag.com
orangepeel.ch
overfitti.ng-dis.co
ourculturemag.com
passiveaggressive.dk
parapop.net
passionweiss.com
palmsout.net
panicmanual.com
pan-african-music.com
pequenosclassicosperdidos.com.br
petalmotel.com
phonographecorp.fr
phonographme.blogspot.pt
pitchfork.com
pilerats.com
pitchup.it
pickymagazine.de
plainorpan.com
plainlyandpainfully.com
post-trash.com
post-punk.com
popmatters.com
postpunkmonk.com
poprockrecord.com
popmuzik.se
poplibnz.wordpress.com
posttowire.com
podcart.co
pouledor.com
thisispoptones.tumblr.com
puddlegum.blog
queencitysoundsandart.wordpress.com
rainbowrodeomag.com
ravensingstheblues.com
rcmndedlisten.com
recordturnover.com
residentadvisor.net
reviler.org
rememberthelightning.substack.com
recorder.blog.hu
retratandovoces.blogspot.com
recordcratesunited.com
recordsilike.wordpress.com
marvin.com.mx
rimasebatidas.pt
riptidemag.fr
rosyoverdrive.com
rocktails.tv
saidthegramophone.com
sos-music.co.uk
secreteclectic.com
self-titledmag.com
slugmag.com
slumbermag.com
bandcampsnoop.tumblr.com
soulbounce.com
sounddoc.net
soundoftheday.co.uk
spectralnights.com
spellbindingmusic.com
spin.com
stereofox.com
stereogum.com
strictlybeats.blogspot.com
start-track.com
stillinrock.com
stationarytravels.wordpress.com
stadiumsandshrines.com
astrangelyisolatedplace.com
stamenspistilsparties.com
myteedjthor.blogspot.com
sixsongs.blogspot.com
survivingthegoldenage.com
supersupersounds.tumblr.com
supportyourlocalghetto.tumblr.com
swinedaily.com
swelltonemusic.com
swedeandsour.tumblr.com
tabsout.com
theslowmusicmovement.org
thefader.com
theobelisk.net
thenewlofi.com
thevinylfactory.com
theautumnroses.org
madmackerel.wordpress.com
thegmanworld.com
thelisteningpostblog.wordpress.com
thedailylistening.com
thediscovertab.substack.com
getalternative.com
theransomnote.com
thenewvinylvillain.wordpress.com
theletter.co.uk
teasesanddares.wordpress.com
terminal313.net
thequietus.com
graintonic.blogspot.com
torturetheartist.net
toneglow.substack.com
tonspion.de
trommelmusic.com
treblezine.com
truantsblog.com
trendingraps.com
iamtunedup.com
twistedsoulmusic.org
twangville.com
ukf.com
umstrum.com
undertheradar.co.nz
undertheradarmag.com
underrated.ru
uptohearmusic.com
varioussmallflames.co.uk
vehlinggo.com
thenewvinylvillain.wordpress.com
villin.net
volt-magazin.de
vrtxmag.com
thevpme.com
welovethat.de
weallwantsomeone.org
whitelight-whiteheat.com
whenwedip.com
thewordisbond.com
whenyoumotoraway.blogspot.com
washmusicmag.com
wavesoverquakes.com
whenthehornblows.com
weownthistown.net
ww2w.fr
welovelofi.tumblr.com
thewire.co.uk
waxmusicuk.wordpress.com
xlr8r.com
xxlmag.com
xsnoize.com
yackmagazine.com
yvynyl.tumblr.com
youhearthat.wordpress.com
zonenights.com
mutantzones.blogspot.com`